// Auto-generated by NSwag - regenerate with: npm run generate-api
// Make sure the backend is running at http://localhost:5110 before running the script

const API_BASE_URL = "http://localhost:5110";

export interface WeatherForecast {
  date: string;
  temperatureC: number;
  temperatureF: number;
  summary: string | null;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;

  constructor(message: string, status: number, response: string) {
    super();
    this.message = message;
    this.status = status;
    this.response = response;
  }
}

export class WeatherForecastClient {
  private baseUrl: string;

  constructor(baseUrl?: string) {
    this.baseUrl = baseUrl ?? API_BASE_URL;
  }

  async getWeatherForecast(signal?: AbortSignal): Promise<WeatherForecast[]> {
    const url = `${this.baseUrl}/WeatherForecast`;

    const response = await fetch(url, {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
      signal,
    });

    if (!response.ok) {
      const text = await response.text();
      throw new ApiException(
        `Error fetching weather forecast: ${response.statusText}`,
        response.status,
        text
      );
    }

    return response.json();
  }
}
