package api

import (
	"encoding/json"
	"net/http"

	"github.com/getkin/kin-openapi/openapi2"
	"github.com/getkin/kin-openapi/openapi2conv"
	"github.com/swaggo/http-swagger"
	"github.com/swaggo/swag"
)

// RegisterSwaggerRoutes exposes the Swagger UI serving an OpenAPI 3.0 document.
// It converts the swagger 2.0 spec generated by swaggo on the fly using kin-openapi.
func (api *Api) RegisterSwaggerRoutes() {
	// Serve converted OpenAPI 3.0 JSON
	api.Router.Get("/swagger/doc.json", api.handleSwaggerDocV3)

	// Swagger UI should fetch the converted doc
	api.Router.Get("/swagger/*", httpSwagger.Handler(httpSwagger.URL("/swagger/doc.json")))
}

func (api *Api) handleSwaggerDocV3(w http.ResponseWriter, r *http.Request) {
	docName := "swagger"

	rawDoc, err := swag.ReadDoc(docName)
	if err != nil || rawDoc == "" {
		http.Error(w, "swagger doc not found", http.StatusInternalServerError)
		return
	}

	var v2 openapi2.T
	if err := json.Unmarshal([]byte(rawDoc), &v2); err != nil {
		http.Error(w, "failed to parse swagger v2 doc", http.StatusInternalServerError)
		return
	}

	v3, err := openapi2conv.ToV3(&v2)
	if err != nil {
		http.Error(w, "failed to convert to openapi v3", http.StatusInternalServerError)
		return
	}

	out, err := json.MarshalIndent(v3, "", "  ")
	if err != nil {
		http.Error(w, "failed to marshal openapi v3", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(out)
}
