/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportResult as ServicesImportResult } from '../../models/services/import-result';

export interface CatserImportPost$Params {
      body?: {

/**
 * Arquivo .xlsx com colunas do CATSER
 */
'file': Blob;
}
}

export function catserImportPost(http: HttpClient, rootUrl: string, params?: CatserImportPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ServicesImportResult>> {
  const rb = new RequestBuilder(rootUrl, catserImportPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ServicesImportResult>;
    })
  );
}

catserImportPost.PATH = '/catser/import';
